### ISSUE TITLE
A ton of empty divs

### ISSUE THREAD

**Issue by AshotN** [aadilhasan/react-async-popup#11]
I was trying out this package, and the page I added a popup to seems to have a ton of empty `<div>` elements in the DOM. This screenshot is the DOM while the popup hasn't been opened yet.

![image](https://user-images.githubusercontent.com/1350342/85915992-b9529600-b83b-11ea-9464-0e14ee7f9591.png)

**Comment by aadilhasan** [comment]
@AshotN  you have to either make prop `destroyOnClose={true}` or you need to call `destroy ` method

`const { show, **destroy** } = await Modal.new(config)`

**Comment by AshotN** [comment]
```
        const { show } = await Modal.new({
            title: 'New Playlist',
            content: (
                <InputModal
                    inputLabel='New Playlist Name'
                    inputPlaceholder='Rock & Roll...'
                    submitButtonText='Create'
                />
            ),
            footer: null,
            popupStyle: {
                minWidth: 400
            }
        });
        const result = await show();

Here is one of my Modals. You can view the entire source code if it helps, it's on https://github.com/ampache/ampache/tree/react-client.

Overall very pleased with the package though. Thank You!
```

**Comment by aadilhasan** [comment]
@AshotN  hey sorry i can't find the file, can you please reproduce it in codesandbox.

**Comment by aadilhasan** [comment]
> ```
>         const { show } = await Modal.new({
>             title: 'New Playlist',
>             content: (
>                 <InputModal
>                     inputLabel='New Playlist Name'
>                     inputPlaceholder='Rock & Roll...'
>                     submitButtonText='Create'
>                 />
>             ),
>             footer: null,
>             popupStyle: {
>                 minWidth: 400
>             }
>         });
>         const result = await show();
> ```
> 
> Here is one of my Modals. You can view the entire source code if it helps, it's on https://github.com/ampache/ampache/tree/react-client.
> 
> Overall very pleased with the package though. Thank You!

@AshotN in this example you must pass `destroyOnClose = true` or call destroy method once you got the result.
I assume this code is being called from a function/method, instead of calling Modal.new( ) again and again in each method call try making this call once in componentDidMount and then save returned values and use them to open and close the modal from the function/method.

If you still want to call Modal.new( ) from a function do it this way - 

```
const { show } = await Modal.new({
           destroyOnClose: true, // do this to automatically destroy the modal on close
            title: 'New Playlist',
            content: (
                <InputModal
                    inputLabel='New Playlist Name'
                    inputPlaceholder='Rock & Roll...'
                    submitButtonText='Create'
                />
            ),
            footer: null,
            popupStyle: {
                minWidth: 400
            }
        });
        const result = await show();
```

OR 


```
const { show, destroy } = await Modal.new({
            title: 'New Playlist',
            content: (
                <InputModal
                    inputLabel='New Playlist Name'
                    inputPlaceholder='Rock & Roll...'
                    submitButtonText='Create'
                />
            ),
            footer: null,
            popupStyle: {
                minWidth: 400
            }
        });
        const result = await show();
       destroy(); // do this to manually destroy the modal.
```

**Comment by AshotN** [comment]
Sorry for my delay, I am going to try to pick back up the codebase that this issue was referencing, and if the issue still exists I will update this issue.
