### ISSUE TITLE
How to pass props component in custom Modal

### ISSUE THREAD

**Issue by AshotN** [aadilhasan/react-async-popup#12]
If I were to use `Modal.new` and put a `content` of a custom component, how do I pass along props to that component? Thanks!

**Comment by aadilhasan** [comment]
@AshotN you can pass prop as you pass to a normal component.

` Modal.new({
   content: <YourComponent prop1={someProp} prop1={someProp}/>
}) `

**Comment by AshotN** [comment]
I think I figured it out, I consoled out the props from the content component, and saw that `ok` and `cancel` were in there. 

If you could tell me what their type would be so I can put it in the interface.

```
interface InputModalParams {
    submitButtonText: string;
    inputPlaceholder?: string;
    inputInitialValue?: string;
    inputLabel: string;
    ok?: any; //TODO
    cancel?: any;
}

```

**Comment by aadilhasan** [comment]
@AshotN Both are functions and if you call cancel then the show method promise will resolve with a false or if you call ok it will resolve with true, and if you call any of them with some data the promise will be resolved with that data.

**Comment by AshotN** [comment]
So would this be an appropriate interface

```
interface PlaylistSelectorProps {
    ok?: (resolve) => Promise<unknown>;
    cancel?: () => Promise<unknown>;
}
```

**Comment by aadilhasan** [comment]
@AshotN This is not correct, ok and cancel, don't return a promise they resolve some other promise (show method promise), so keep them both as a function.
